test:
  image: python:bullseye
  tags:
    - self-hosted
    - host-arm64
  script:
    - python3 -m pip install --upgrade pip
    - if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
    - pytest -v --junit-xml report.xml
  artifacts:
    paths:
      - "*.xml"
