#!/usr/bin/env python3

import glob
import json

revpi_hat_templates = sorted(glob.glob('./revpi-hat-PR*.json'))


readme = """<details>
<summary>We have moved to GitLab! Read this for more information.</summary>

We have recently moved our repositories to GitLab. You can find revpi-hat-data
here: https://gitlab.com/revolutionpi/revpi-hat-data  
All repositories on GitHub will stay up-to-date by being synchronised from
GitLab.

We still maintain a presence on GitHub but our work happens over at GitLab. If
you want to contribute to any of our projects we would prefer this contribution
to happen on GitLab, but we also still accept contributions on GitHub if you
prefer that.
</details>

# revpi-hat-eeprom-files

![Plausibility checks CI badge](https://github.com/RevolutionPi/revpi-hat-data/actions/workflows/templates.yml/badge.svg)

Device specific JSON templates for RevPi HAT EEPROM generation

| Device | Vendor | Product Id | Product Revision | Data Version | Devicetree Overlay |
| ------ | ------ | ---------- | ---------------- | ------------ | ------------------ |
"""

for template in revpi_hat_templates:
    with open(template, 'r') as f:
        template_data = json.loads(f.read())

        name = template_data["pstr"]
        product_id = template_data["pid"] + 100000
        vendor = template_data["vstr"]
        product_revision = template_data["prev"]
        data_version = template_data["eeprom_data_version"]
        overlay = template_data["dtstr"]

        readme += f"| [{name }]({template}) | {vendor} | PR{product_id} | R{product_revision:02} | {data_version} | {overlay} |\n"

readme += "\n\n**Please note that this README file is auto-generated by the `scripts/update-readme.py` script. More details can be found [here](scripts/README.md)**"


with open("README.md", "w") as f:
    f.write(readme)
